[[constraint]]
  branch = "master"
  name = "github.com/buger/jsonparser"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
